image: registry.gitlab.com/collectivecloud/docker-builds/dependencies

# Select what we should cache between builds
cache:
  paths:
    - vendor/

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: mysql_database
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  NEXTCLOUD_SOURCE: '/var/www/html'

unit:
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - ln -s `pwd` $NEXTCLOUD_SOURCE/apps/wiki
  services:
    - mysql:5.7

integration:
  script:
    - vendor/bin/behat --config=tests/Integration/config/behat.yml --profile ci
  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - ln -s `pwd` $NEXTCLOUD_SOURCE/apps/wiki
    - sudo -u www-data $NEXTCLOUD_SOURCE/occ app:enable wiki
    - INTERNAL_IP_ADDRESS="$(ip a show type veth | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")"
    - echo "$INTERNAL_IP_ADDRESS nextcloud.local" >>/etc/hosts
    - /etc/init.d/apache2 start
  services:
    - mysql:5.7

lint:
  image: node
  script:
    - npm run lint
  before_script:
    - npm install
