name: Cypress

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'appinfo/**'
      - 'cypress/**'
      - 'l10n/**'
      - 'lib/**'
      - 'src/**'
      - 'skeleton/**'
      - 'templates/**'
      - '.php-cs-fixer.dist.php'
      - 'babel.config.js'
      - 'composer.json'
      - 'composer.lock'
      - 'cypress.json'
      - 'package.json'
      - 'package-lock.json'

  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: collectives
  CYPRESS_baseUrl: http://localhost:8081/index.php

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        containers: [1, 2, 3, 4]
        php-versions: ['8.0']
        databases: ['sqlite']
        server-versions: ['stable25', 'master']

    steps:
      - name: Set app env
        run: |
          # Split and keep last
          echo "APP_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Checkout server
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout circles app
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: nextcloud/circles
          path: apps/circles
          ref: ${{ matrix.server-versions }}

      - name: Checkout files_pdfviewer app
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: nextcloud/files_pdfviewer
          path: apps/files_pdfviewer
          ref: ${{ matrix.server-versions }}

      - name: Register text Git reference
        run: |
          text_app_ref="$(if [ "${{ matrix.server-versions }}" = "master" ]; then echo -n "main"; else echo -n "${{ matrix.server-versions }}"; fi)"
          echo "text_app_ref=$text_app_ref" >> $GITHUB_ENV

      - name: Checkout text app
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: nextcloud/text
          path: apps/text
          ref: ${{ env.text_app_ref }}

      - name: Checkout viewer app
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: nextcloud/viewer
          path: apps/viewer
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: ${{ matrix.php-versions }}
          # https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i --no-dev

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@0ce2ed60f6df073a62a77c0a4958dd0fc68e32e7 # v2.1
        id: versions
        with:
          fallbackNode: '^16'
          fallbackNpm: '^8'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          cache: 'npm'
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Install dependencies & build
        working-directory: apps/${{ env.APP_NAME }}
        run: |
          npm ci
          npm run build --if-present

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          ./occ app:enable --force contacts
          ./occ app:enable --force files_pdfviewer
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: Add Nextcloud users and a collective for full-text search
        run: |
          for user in alice bob jane john; do \
          OC_PASS="$user" ./occ user:add --password-from-env "$user"; \
          done
          ./occ group:add "Bobs Group"
          for user in bob jane; do \
          OC_PASS="$user" ./occ group:adduser "Bobs Group" "$user"; \
          done
          ./occ collectives:create SearchTest --owner=bob
          ./occ collectives:index

      - name: Run Nextcloud
        run: php -S 0.0.0.0:8081 &

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          parallel: true
          wait-on: '${{ env.CYPRESS_baseUrl }}'
          working-directory: apps/${{ env.APP_NAME }}
          config: video=false,defaultCommandTimeout=20000
          tag: ${{ github.event_name }}
        env:
          # https://github.com/cypress-io/github-action/issues/124
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA:  ${{ github.event.pull_request.head.sha }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_ncVersion: ${{ matrix.server-versions }}

      - name: Upload test failure screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Upload screenshots
          path: apps/${{ env.APP_NAME }}/cypress/screenshots/
          retention-days: 5

      - name: Upload nextcloud logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Upload nextcloud log
          path: data/nextcloud.log
          retention-days: 5

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: cypress

    if: always()

    name: cypress-summary

    steps:
      - name: Summary status
        run: if ${{ needs.cypress.result != 'success' }}; then exit 1; fi
